export const ORDER_CREAT_REQYEST ='ORDER_CREAT_REQYEST'
export const ORDER_CREAT_SUCCESS ='ORDER_CREAT_SUCCESS'
export const ORDER_CREAT_FAIL ='ORDER_CREAT_FAIL'
export const ORDER_CREAT_RESET ='ORDER_CREAT_RESET'