export const ORDER_CREATE_REQUEST ='ORDER_CREAT_REQYEST'
export const ORDER_CREATE_SUCCESS ='ORDER_CREAT_SUCCESS'
export const ORDER_CREATE_FAIL ='ORDER_CREAT_FAIL'
export const ORDER_CREATE_RESET ='ORDER_CREAT_RESET'